meta_product_name: "Bin here?"
meta_title: "Bin here? - Trier ou vous vivez, quand vous voullez, sans vous tromper."
meta_description: "Bin here est une application de géolocalisation des poubelles, choisissez votre déchet et nous vous trouvons les poubelles appropriées autour de vous."
meta_image: "metaimage.png"
twitter_account: "@RegemanSW6"
